AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: String
  CodeKey:
    Type: String
  AwsKey:
    Type: String
  AwsSecret:
    Type: String
  FanduelApiRoot:
    Type: String
Globals:
  Function:
    MemorySize: 512
    Timeout: 900

Resources:
  MergeDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: mergeData.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          AWS_KEY: !Ref AwsKey
          AWS_SECRET: !Ref AwsSecret
  ScheduleStateMachinesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: scheduleStateMachines.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          AWS_KEY: !Ref AwsKey
          AWS_SECRET: !Ref AwsSecret
          FANDUEL_API_ROOT: !Ref FanduelApiRoot